apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deployment
  namespace: technical-test
  labels:
    app: goapp
    type: front-end
spec:
  #pod template
  template:
    metadata:
      name: goapp-pod
      labels:
        app: goapp
        type: front-end
    spec:
      containers:
        - name: goapp-container
          image: goapp_image
          imagePullPolicy: IfNotPresent
          securityContext:
            #runAsUser: 1000
            capabilities:
              drop:
                - all
              add: ["NET_BIND_SERVICE", "NET_RAW"]
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /version
              port: 3000
            periodSeconds: 300
          volumeMounts:
            - mountPath: /var/log/goapp
              name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-claim
  replicas: 2
  selector:
    matchLabels:
      app: goapp
      type: front-end
