apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
  namespace: technical-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 200Mi

