apiVersion: v1
kind: Service
metadata:
  name: goapp-service
  namespace: technical-test

spec:
  type: NodePort
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30008
  selector:
    app: goapp
    type: front-end